#!/usr/bin/env bash

usage() {
   echo "Usage: $0 -d DEVICE [ -m MODE ]"
   echo "   Mode must be one of hourly, minutely or secondly"
   echo
   echo "Example: ponyclock /dev/ttyUSB0"
   exit 1
}

while [[ $# > 1 ]]; do
   key="$1"
   shift
   case $key in
      -d|--device)
         PONYDEVICE=$1
         shift
         ;;
      -m|--mode)
         MODE="$1"
         if [ "$MODE" != "hourly" ] && [ "$MODE" != "minutely" ] && [ "$MODE" != "secondly" ]; then
            usage
         fi
         shift
         ;;
      *)
         usage
      ;;
   esac
done

if [ ! -c "$PONYDEVICE" ]; then
   usage
fi

while true; do
   itis=$(printf '%03d\n' 0x$(date +%H))
   if [ "$MODE" == "hourly" ]; then
      itis+="000000"
      SLEEPTIME=3600
   elif [ "$MODE" == "minutely" ]; then
      itis+=$(printf '%03d\n' 0x$(date +%M))000
      SLEEPTIME=60
   else
      itis+=$(printf '%03d\n' 0x$(date +%M))
      itis+=$(printf '%03d\n' 0x$(date +%S))
      SLEEPTIME=1
   fi
   ponytool $PONYDEVICE SET $itis
   sleep $SLEEPTIME
done

